In [1]:
import ABIDEParser as Reader


In [2]:
import numpy as np

In [3]:
# Get class labels
subject_IDs = Reader.get_ids()
labels = Reader.get_subject_score(subject_IDs, score='DX_GROUP')

# Get acquisition site
sites = Reader.get_subject_score(subject_IDs, score='SITE_ID')
unique = np.unique(list(sites.values())).tolist()

num_classes = 2
num_nodes = len(subject_IDs)

# Initialise variables for class labels and acquisition sites
y_data = np.zeros([num_nodes, num_classes])
y = np.zeros([num_nodes, 1])
site = np.zeros([num_nodes, 1], dtype=int)

# Get class labels and acquisition site for all subjects
for i in range(num_nodes):
    y_data[i, int(labels[subject_IDs[i]])-1] = 1
    y[i] = int(labels[subject_IDs[i]])
    site[i] = unique.index(sites[subject_IDs[i]])

In [4]:
# Compute feature vectors (vectorised connectivity networks)
features = Reader.get_networks(subject_IDs, kind='correlation', atlas_name='ho')

# Compute population graph using gender and acquisition site
# graph = Reader.create_affinity_graph_from_scores(['SEX', 'SITE_ID'], subject_IDs)

c:\PFA\population-gcn2\ABIDEParser.py:224: RuntimeWarning: divide by zero encountered in arctanh
  norm_networks = [np.arctanh(mat) for mat in all_networks]


In [21]:
features

array([[ 0.97663709,  0.82530072,  0.74820651, ...,  0.91433765,
         0.76759212,  1.1123392 ],
       [ 0.62647921,  0.68386934,  0.49554931, ..., -0.01265819,
         0.08046417,  0.85968089],
       [ 0.52387629,  0.39586813,  0.356258  , ...,  0.69001642,
         0.72559831,  1.37230362],
       ...,
       [ 0.28196335,  0.62367273,  0.59732468, ...,  0.33613925,
         0.35266004,  1.26734374],
       [ 0.3318541 ,  0.3479959 ,  0.54438837, ...,  0.21702285,
         0.29280098,  0.63961068],
       [ 0.61490946,  0.86683146,  0.77573038, ...,  0.22311195,
         0.35032753,  1.03944121]])

In [5]:
features.shape

(871, 6105)

In [8]:
y

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train , x_test = train_test_split(features,train_size=0.8)
y_train, y_test = train_test_split(y,train_size=0.8)

In [20]:
x_train[0]

array([0.41085447, 0.64180798, 0.69412695, ..., 0.36272488, 0.31732485,
       1.270975  ])

In [11]:
from sklearn.utils.validation import column_or_1d
y_train=column_or_1d(y_train, warn=True)


C:\Users\ousem\AppData\Local\Temp\ipykernel_12876\2359269923.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_train=column_or_1d(y_train, warn=True)


In [12]:
y_train.shape

(696,)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
clf = LogisticRegression().fit(x_train, y_train)

c:\Users\ousem\.virtualenvs\population-gcn2-YZL6I4UQ\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
pred = clf.predict(x_test)

In [16]:
pred

array([1., 2., 1., 2., 1., 2., 1., 2., 2., 2., 1., 1., 1., 2., 2., 1., 1.,
       2., 2., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 1., 1., 2., 1.,
       1., 2., 2., 2., 2., 2., 2., 2., 1., 1., 2., 1., 1., 1., 2., 2., 1.,
       1., 1., 2., 2., 2., 1., 2., 1., 2., 2., 1., 2., 2., 2., 2., 1., 2.,
       1., 1., 2., 2., 2., 1., 1., 2., 1., 2., 2., 2., 2., 1., 2., 1., 2.,
       2., 1., 2., 2., 1., 2., 1., 1., 2., 2., 2., 1., 2., 2., 1., 1., 1.,
       2., 1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 2., 1., 1., 1.,
       1., 1., 1., 2., 1., 1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1.,
       1., 2., 1., 1., 1., 1., 1., 2., 2., 2., 1., 2., 1., 2., 2., 1., 2.,
       1., 2., 1., 1., 2., 1., 2., 1., 1., 2., 2., 1., 2., 1., 1., 2., 1.,
       2., 1., 2., 1., 2.])

In [17]:
clf.score(x_test,y_test)

0.45714285714285713

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
knn = KNeighborsClassifier(5)
knn.fit(x_train,y_train)
knn.score(x_train,y_train)
y_pred_knn = knn.predict(x_test)